import type { Metadata } from 'next';
import { inter, panchang, satoshi, pump_triline, inconsolata, triangulate } from '@/fonts';
import '@/app/globals.css';
import { SmoothScrolling, NavBar, Footer } from '@/components/shared';
import { PhaseOrchestrator } from '@/components/shared/PhaseOrchestrator';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ transition: 'color 0.5s ease, background-color 0.5s ease' }}
        className={`${inter.variable} ${panchang.variable} ${satoshi.variable} 
      ${pump_triline.variable} ${pump_triline.variable} ${panchang.variable} 
      ${satoshi.variable} ${pump_triline.variable} ${inconsolata.variable} ${triangulate.variable} light`}
      >
        <SmoothScrolling />
        <PhaseOrchestrator />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
